import pandas as pd

df = pd.read_csv("data/accepted_2007_to_2018.csv", low_memory=False)

df2 = df[[
    # Target variable
    "loan_status",
    # Credit profile
    "fico_range_low", "fico_range_high", "grade", "sub_grade",
    "delinq_2yrs", "inq_last_6mths",
    # Debt & Income metrics
    "dti", "annual_inc", "revol_util",
    # Loan specifics
    "loan_amnt", "int_rate", "term", "purpose",
    # Credit history
    "earliest_cr_line", "total_acc", "open_acc",
    "mths_since_last_delinq", "mths_since_last_major_derog"
]]

df2.to_csv("data/lending_subset.csv", index=False)

# Lending Club Loan Performance & Risk Analysis (2007–2018)

Peer-to-peer lending platforms must carefully evaluate borrower risk while maintaining profitability. Poor credit risk assessment can lead to high default rates, reducing investor confidence and financial sustainability.

Lending companies need to understand which borrower characteristics, loan attributes, and economic factors are associated with higher default rates and lower loan performance.

Using historical lending data from Lending Club (2007-2018), this project analyzes loan performance to identify patterns in borrower behavior, loan characteristics, and repayment outcomes. The goal is to generate actionable insights that can help lending companies:

- Identify high-risk borrower profiles

- Understand the relationship between loan characteristics and default rates

- Evaluate the profitability of different loan segments

- Improve lending strategies and risk management decisions

The analysis uses Python for data exploration and cleaning, SQL for business queries, and Power BI to build an interactive dashboard for financial insights.

# Importing dataset

I downloaded the full dataset but for knowledge purposes I'll simulate a SQL database extraction and different SQL queries.

In [8]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [9]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:postgresdb@localhost:5432/lending_analysis")

def run_query(query):
    return pd.read_sql_query(query, engine)

In [16]:
query = """
SELECT 
    loan_status,
    COUNT(*) AS total_loans
FROM loans
GROUP BY loan_status
ORDER BY total_loans DESC;
"""

total_loans_by_status = run_query(query)
total_loans_by_status

                                         loan_status  total_loans
0                                         Fully Paid      1076751
1                                            Current       878317
2                                        Charged Off       268559
3                                 Late (31-120 days)        21467
4                                    In Grace Period         8436
5                                  Late (16-30 days)         4349
6  Does not meet the credit policy. Status:Fully ...         1988
7  Does not meet the credit policy. Status:Charge...          761
8                                            Default           40
9                                                NaN           33

In [18]:
query = """
SELECT 
    loan_status,
    AVG(loan_amnt) AS avg_loan_amount
FROM loans
GROUP BY loan_status
ORDER BY avg_loan_amount DESC;
"""

average_loan_amount_by_loan_status = run_query(query)
average_loan_amount_by_loan_status

                                         loan_status  avg_loan_amount
0                                                NaN              NaN
1                                    In Grace Period     17672.558084
2                                  Late (16-30 days)     17391.118648
3                                 Late (31-120 days)     16946.614571
4                                            Current     15942.815920
5                                        Charged Off     15565.055444
6                                            Default     14350.625000
7                                         Fully Paid     14134.369808
8  Does not meet the credit policy. Status:Charge...      9527.233903
9  Does not meet the credit policy. Status:Fully ...      8853.231891